---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ok-to-test"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
        interval: "weekly"
    labels:
      - "ok-to-test"
