sudo: required
dist: trusty

language: go

go:
- 1.6.2
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libvirt-dev
# We shouldn't need to install anything because we use vendoring.
install:
- echo "Don't run anything."

# Run unit tests and linters.
script: make test
