language: go
os: linux

matrix:
  include:
    - go: 1.x
    - language: python
      before_install: pip install flake8
      script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

before_install:
  - sudo apt-get install -y libvirt-dev
install:
  - echo "Don't run anything."
script:
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
