os: linux
language: go
go:
  - 1.12.9

env:
  global:
    - GOPROXY=https://proxy.golang.org
matrix:
  include:
    - language: python
      env:
        - TESTSUITE_BOILERPLATE=true
      before_install: 
          - pip install flake8 && flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      script: make test

    - language: go
      go: 1.12.9
      env:
        - TESTSUITE_LINT=true
      before_install:
        - sudo apt-get install -y libvirt-dev
      script: make test

    - language: go
      go: 1.12.9
      env:
        - TESTSUITE_UNIT=true
      before_install:
        - sudo apt-get install -y libvirt-dev
      script: make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
    webhooks: https://www.travisbuddy.com/
    on_success: never # travisbuddy don't comment on successful 