---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: hello
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
      containers:
        - name: main
          image: strm/helloworld-http
          ports:
            - containerPort: 80
              name: http
      terminationGracePeriodSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
