addons:
  - embedfs://addon.AutoPauseAssets/auto-pause/auto-pause.addon.yaml
  - embedfs://addon.DashboardAssets/dashboard/dashboard.addon.yaml
  - embedfs://addon.DefaultStorageClassAssets/storageclass/default-storageclass.addon.yaml
  - embedfs://addon.PodSecurityPolicyAssets/pod-security-policy/pod-security-policy.addon.yaml
  - embedfs://addon.StorageProvisionerAssets/storage-provisioner/storage-provisioner.addon.yaml
  - embedfs://addon.StorageProvisionerGlusterAssets/storage-provisioner-gluster/storage-provisioner-gluster.addon.yaml
  - embedfs://addon.EfkAssets/efk/efk.addon.yaml
  - embedfs://addon.IngressAssets/ingress/ingress.addon.yaml
  - embedfs://addon.IstioProvisionerAssets/istio-provisioner/istio-provisioner.addon.yaml
  - embedfs://addon.IstioAssets/istio/istio.addon.yaml
  - embedfs://addon.KubevirtAssets/kubevirt/kubevirt.addon.yaml
  - embedfs://addon.MetricsServerAssets/metrics-server/metrics-server.addon.yaml
  - embedfs://addon.OlmAssets/olm/olm.addon.yaml
  - embedfs://addon.RegistryAssets/registry/registry.addon.yaml
  - embedfs://addon.RegistryCredsAssets/registry-creds/registry-creds.addon.yaml
  - embedfs://addon.RegistryAliasesAssets/registry-aliases/registry-aliases.addon.yaml
  - embedfs://addon.FreshpodAssets/freshpod/freshpod.addon.yaml
  - embedfs://addon.NvidiaDriverInstallerAssets/gpu/nvidia-driver-installer.addon.yaml
  - embedfs://addon.NvidiaGpuDevicePluginAssets/gpu/nvidia-gpu-device-plugin.addon.yaml
  - embedfs://addon.LogviewerAssets/logviewer/logviewer.addon.yaml
  - embedfs://addon.GvisorAssets/gvisor/gvisor.addon.yaml
  - embedfs://addon.HelmTillerAssets/helm-tiller/helm-tiller.addon.yaml
  - embedfs://addon.IngressDNSAssets/ingress-dns/ingress-dns.addon.yaml
  - embedfs://addon.MetallbAssets/metallb/metallb.addon.yaml
  - embedfs://addon.AmbassadorAssets/ambassador/ambassador.addon.yaml
  - embedfs://addon.GcpAuthAssets/gcp-auth/gcp-auth.addon.yaml
  - embedfs://addon.VolumeSnapshotsAssets/volumesnapshots/volumesnapshots.addon.yaml
  - embedfs://addon.CsiHostpathDriverAssets/csi-hostpath-driver/csi-hostpath-driver.addon.yaml
  - embedfs://addon.PortainerAssets/portainer/portainer.addon.yaml
