apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: monitoring-grafana
    kubernetes.io/minikube-addons: heapster
    kubernetes.io/minikube-addons-endpoint: heapster
    addonmanager.kubernetes.io/mode: Reconcile
  name: monitoring-grafana
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
    targetPort: ui
  selector:
    addonmanager.kubernetes.io/mode: Reconcile
    name: influxGrafana
