
apiVersion: v1
kind: ReplicationController
metadata:
  name: registry-creds
  namespace: kube-system
  labels:
    app: registry-creds
    version: v1.1
    kubernetes.io/cluster-service: "true"
    kubernetes.io/minikube-addons: registry-creds
spec:
  replicas: 1
  selector:
    app: registry-creds
    version: v1.4
    kubernetes.io/cluster-service: "true"
  template:
    metadata:
      labels:
        app: registry-creds
        version: v1.4
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - image: upmcenterprises/registry-creds:1.4
        name: registry-creds
        imagePullPolicy: Always
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: registry-creds
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: registry-creds
                key: AWS_SECRET_ACCESS_KEY
          - name: awsaccount
            valueFrom:
              secretKeyRef:
                name: registry-creds
                key: aws-account