name: English
description: Report an issue
body:
  - type: textarea
    id: problem
    attributes:
      label: What Happened?
      description: |
        Tip: Add the "--alsologtostderr" flag to the command-line for more logs
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Attach the log file
      description: |
        Tip: Run `minikube logs --file=log.txt` then drag & drop `log.txt` file to the browser.
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What is your OS?
      options:
        - macOS (Default)
        - Windows
        - Ubuntu
        - Redhat/Fedora
        - Other
    validations:
      required: false
  - type: dropdown
    id: driver
    attributes:
      label: Driver
      description: What driver do you use?
      options:
        - N/A
        - Docker
        - Podman
        - HyperKit
        - Hyper-V
        - KVM2
        - VirtualBox
        - None (Baremetal)
        - SSH
        - VMware
        - Parallels
    validations:
      required: false
