apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: hello-world-app
          image: gcr.io/google-samples/hello-app:1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-loadbalanced-service
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hello-world.demo
spec:
  selector:
    app: hello-world-app
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-internal-service
  namespace: default
spec:
  selector:
    app: hello-world-app
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: hello-john.demo
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world-internal-service
                port:
                  number: 80
    - host: hello-jane.demo
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world-internal-service
                port:
                  number: 80
