
apiVersion: v1
kind: ReplicationController
metadata:
  name: awsecr-creds
  namespace: kube-system
  labels:
    app: awsecr-creds
    version: v1.1
    kubernetes.io/cluster-service: "true"
    kubernetes.io/minikube-addons: awsecr-creds
spec:
  replicas: 1
  selector:
    app: awsecr-creds
    version: v1.1
    kubernetes.io/cluster-service: "true"
  template:
    metadata:
      labels:
        app: awsecr-creds
        version: v1.1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - image: upmcenterprises/awsecr-creds:1.1
        name: awsecr-creds
        imagePullPolicy: Always
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: awsecr-creds
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: awsecr-creds
                key: AWS_SECRET_ACCESS_KEY
          - name: awsaccount
            valueFrom:
              secretKeyRef:
                name: awsecr-creds
                key: aws-account