on: pull_request
name: integration docker on ubuntu 
jobs:
  build:
    name: run integration test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: run test
        run: env TEST_ARGS="-minikube-start-args=--vm-driver=docker" make integration
