name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest # action can only be run on windows
    steps:
      - uses: vedantmgoyal2009/winget-releaser@b9b77fcdf4521de93fbe1ebeb7e64b159dba0adf
        with:
          identifier: Kubernetes.minikube
          installers-regex: 'minikube-installer.exe'
          token: ${{ secrets.WINGET_TOKEN }}
          fork-user: minikube-bot
